--The scrips write a sort information about the state of disks.

set linesize 400;
COLUMN PATH  FORMAT a15 heading PATH
COLUMN NAME FORMAT a8 heading NAME
COLUMN GROUP_NUMBER FORMAT 99 heading GR_NUM
COLUMN DISK_NUMBER  FORMAT 99 heading DISK_NUM
COLUMN MOUNT_STATUS FORMAT a9 heading "MOUNT|STATUS"
COLUMN HEADER_STATUS FORMAT a11 heading "HEADER|STATUS";
COLUMN MODE_STATUS FORMAT a6 heading "MODE|STATUS";
COLUMN REDUNDANCY FORMAT a10 heading REDUNDANCY;
COLUMN FAILGROUP FORMAT a6 heading FAILGR;


select
NAME,
PATH,
GROUP_NUMBER,
DISK_NUMBER,
MOUNT_STATUS,
HEADER_STATUS,
MODE_STATUS,
REDUNDANCY,
FAILGROUP
from v$asm_disk;
